const app = angular.module("myApp", [])

app.controller("myController", function ($scope) {
    $scope.name = "used of limitTo📈"
    $scope.fruits = [
        "Apple",
        "Banana",
        "Mango",
        "Orange",
        "Grapes",
        "Pineapple",
        "Watermelon",
        "Strawberry",
        "Papaya",
        "Guava",
        "Pomegranate",
        "Kiwi"
    ];

    $scope.students = [
        {
            id: 1,
            name: "Aarav Sharma",
            age: 20,
            gender: "Male",
            course: "BCA",
            semester: 4,
            city: "Vadodara",
            email: "aarav.sharma@example.com",
            phone: "9876543210",
            marks: 86,
            grade: "A",
            subjects: ["JavaScript", "HTML", "CSS", "Database"],
        },
        {
            id: 2,
            name: "Diya Patel",
            age: 19,
            gender: "Female",
            course: "BCA",
            semester: 3,
            city: "Ahmedabad",
            email: "diya.patel@example.com",
            phone: "9876543211",
            marks: 92,
            grade: "A+",
            subjects: ["JavaScript", "Python", "Database", "Networking"],

        },
        {
            id: 3,
            name: "Rohan Mehta",
            age: 21,
            gender: "Male",
            course: "BSc IT",
            semester: 5,
            city: "Surat",
            email: "rohan.mehta@example.com",
            phone: "9876543212",
            marks: 78,
            grade: "B+",
            subjects: ["Java", "PHP", "Database", "Web Development"],

        },
        {
            id: 4,
            name: "Ananya Shah",
            age: 20,
            gender: "Female",
            course: "BCA",
            semester: 4,
            city: "Rajkot",
            email: "ananya.shah@example.com",
            phone: "9876543213",
            marks: 95,
            grade: "A+",
            subjects: ["JavaScript", "React", "CSS", "UI Design"],

        },
        {
            id: 5,
            name: "Vivaan Desai",
            age: 22,
            gender: "Male",
            course: "MCA",
            semester: 2,
            city: "Vadodara",
            email: "vivaan.desai@example.com",
            phone: "9876543214",
            marks: 81,
            grade: "A",
            subjects: ["Node.js", "MongoDB", "Express", "JavaScript"],

        },
        {
            id: 6,
            name: "Ishita Joshi",
            age: 19,
            gender: "Female",
            course: "BSc IT",
            semester: 3,
            city: "Gandhinagar",
            email: "ishita.joshi@example.com",
            phone: "9876543215",
            marks: 88,
            grade: "A",
            subjects: ["Python", "Data Science", "Statistics", "SQL"],

        },
        {
            id: 7,
            name: "Arjun Trivedi",
            age: 21,
            gender: "Male",
            course: "BCA",
            semester: 5,
            city: "Anand",
            email: "arjun.trivedi@example.com",
            phone: "9876543216",
            marks: 74,
            grade: "B",
            subjects: ["Java", "C++", "Operating System", "Networking"],
            isActive: false
        },
        {
            id: 8,
            name: "Myra Bhatt",
            age: 20,
            gender: "Female",
            course: "BCA",
            semester: 4,
            city: "Bhavnagar",
            email: "myra.bhatt@example.com",
            phone: "9876543217",
            marks: 90,
            grade: "A+",
            subjects: ["HTML", "CSS", "JavaScript", "AngularJS"],

        },
        {
            id: 9,
            name: "Kabir Patel",
            age: 22,
            gender: "Male",
            course: "MCA",
            semester: 3,
            city: "Ahmedabad",
            email: "kabir.patel@example.com",
            phone: "9876543218",
            marks: 83,
            grade: "A",
            subjects: ["Java", "Spring Boot", "MySQL", "REST API"],

        },
        {
            id: 10,
            name: "Siya Modi",
            age: 19,
            gender: "Female",
            course: "BSc IT",
            semester: 2,
            city: "Surat",
            email: "siya.modi@example.com",
            phone: "9876543219",
            marks: 97,
            grade: "A+",
            subjects: ["Python", "HTML", "CSS", "JavaScript"],

        },
        {
            id: 11,
            name: "Dev Malhotra",
            age: 21,
            gender: "Male",
            course: "BCA",
            semester: 6,
            city: "Vadodara",
            email: "dev.malhotra@example.com",
            phone: "9876543220",
            marks: 69,
            grade: "B",
            subjects: ["PHP", "MySQL", "Laravel", "JavaScript"],
            isActive: false
        },
        {
            id: 12,
            name: "Avni Kapoor",
            age: 20,
            gender: "Female",
            course: "BCA",
            semester: 5,
            city: "Nadiad",
            email: "avni.kapoor@example.com",
            phone: "9876543221",
            marks: 89,
            grade: "A",
            subjects: ["AngularJS", "JavaScript", "TypeScript", "MongoDB"],

        }
    ];
})